Rails/MyDemos/school/config/routes.rb
School::Application.routes.draw do
  resources :pupils

end

Rails/MyDemos/school/app/models/pupil.rb
class Pupil < ActiveRecord::Base
  attr_accessible :form, :name
end

Rails/MyDemos/school/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Rails/MyDemos/school/app/controllers/pupils_controller.rb
class PupilsController < ApplicationController
  # GET /pupils
  # GET /pupils.json
  def index
    @pupils = Pupil.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pupils }
    end
  end

  # GET /pupils/1
  # GET /pupils/1.json
  def show
    @pupil = Pupil.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pupil }
    end
  end

  # GET /pupils/new
  # GET /pupils/new.json
  def new
    @pupil = Pupil.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pupil }
    end
  end

  # GET /pupils/1/edit
  def edit
    @pupil = Pupil.find(params[:id])
  end

  # POST /pupils
  # POST /pupils.json
  def create
    @pupil = Pupil.new(params[:pupil])

    respond_to do |format|
      if @pupil.save
        format.html { redirect_to @pupil, notice: 'Pupil was successfully created.' }
        format.json { render json: @pupil, status: :created, location: @pupil }
      else
        format.html { render action: "new" }
        format.json { render json: @pupil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pupils/1
  # PUT /pupils/1.json
  def update
    @pupil = Pupil.find(params[:id])

    respond_to do |format|
      if @pupil.update_attributes(params[:pupil])
        format.html { redirect_to @pupil, notice: 'Pupil was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pupil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pupils/1
  # DELETE /pupils/1.json
  def destroy
    @pupil = Pupil.find(params[:id])
    @pupil.destroy

    respond_to do |format|
      format.html { redirect_to pupils_url }
      format.json { head :no_content }
    end
  end
end

Rails/MyDemos/school/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/MyDemos/school/app/helpers/pupils_helper.rb
module PupilsHelper
end

Rails/MyDemos/school/app/views/pupils/_form.html.erb
<%= form_for(@pupil) do |f| %>
  <% if @pupil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pupil.errors.count, "error") %> prohibited this pupil from being saved:</h2>

      <ul>
      <% @pupil.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :form %><br />
    <%= f.text_field :form %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/MyDemos/school/app/views/pupils/edit.html.erb
<h1>Editing pupil</h1>

<%= render 'form' %>

<%= link_to 'Show', @pupil %> |
<%= link_to 'Back', pupils_path %>

Rails/MyDemos/school/app/views/pupils/index.html.erb
<h1>Listing pupils</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Form</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pupils.each do |pupil| %>
  <tr>
    <td><%= pupil.name %></td>
    <td><%= pupil.form %></td>
    <td><%= link_to 'Show', pupil %></td>
    <td><%= link_to 'Edit', edit_pupil_path(pupil) %></td>
    <td><%= link_to 'Destroy', pupil, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pupil', new_pupil_path %>

Rails/MyDemos/school/app/views/pupils/new.html.erb
<h1>New pupil</h1>

<%= render 'form' %>

<%= link_to 'Back', pupils_path %>

Rails/MyDemos/school/app/views/pupils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @pupil.name %>
</p>

<p>
  <b>Form:</b>
  <%= @pupil.form %>
</p>


<%= link_to 'Edit', edit_pupil_path(@pupil) %> |
<%= link_to 'Back', pupils_path %>